version: "3.7"
name: laravel-docker-teste

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app

  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - app

networks:
  app:
    driver: bridge
